// ============================================================================
// PPW Email Engine — Email Template Generator
// Generates Klaviyo-ready email copy with dynamic tags and conditional blocks
// for each position in the 45-day nurture flow.
// ============================================================================

import { CATEGORIES, Category } from "./categories";
import { NURTURE_EMAIL_POSITIONS, EmailPosition, CATEGORY_CONTENT } from "./content-map";
import { buildAssetName } from "./naming";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface KlaviyoVariable {
  tag: string;
  description: string;
  fallback?: string;
  example: string;
}

export interface ConditionalBlock {
  condition: string;
  description: string;
  trueContent: string;
  falseContent?: string;
}

export interface EmailTemplate {
  /** PPW naming convention: T-[CAT]-[Flow]-[E#] */
  templateName: string;
  /** Email position in the nurture flow */
  position: string;
  /** Day in the 45-day sequence */
  day: number;
  /** Category code */
  categoryCode: string;
  /** Category name */
  categoryName: string;
  /** Email subject line with Klaviyo tags */
  subject: string;
  /** Preview text */
  previewText: string;
  /** HTML body with Klaviyo tags and conditional blocks */
  htmlBody: string;
  /** Plain-text version */
  plainText: string;
  /** All Klaviyo dynamic variables used */
  variables: KlaviyoVariable[];
  /** Conditional blocks used */
  conditionals: ConditionalBlock[];
  /** Purpose from the nurture flow */
  purpose: string;
}

// ---------------------------------------------------------------------------
// Klaviyo Variable Registry
// ---------------------------------------------------------------------------

export const KLAVIYO_VARIABLES: KlaviyoVariable[] = [
  {
    tag: '{{ first_name|default:"there" }}',
    description: "Subscriber's first name with fallback",
    fallback: "there",
    example: "Sarah",
  },
  {
    tag: "{{ person.first_name }}",
    description: "Subscriber's first name (no fallback)",
    example: "Sarah",
  },
  {
    tag: "{{ person.email }}",
    description: "Subscriber's email address",
    example: "sarah@example.com",
  },
  {
    tag: "{{ top_recommendation }}",
    description: "Top product recommendation from quiz",
    example: "Golden Designs 2-Person Full Spectrum Sauna",
  },
  {
    tag: "{{ top_recommendation_url }}",
    description: "URL to top recommended product",
    example: "https://peakprimalwellness.com/products/golden-designs-2p",
  },
  {
    tag: "{{ top_recommendation_image }}",
    description: "Image URL of top recommended product",
    example: "https://cdn.shopify.com/s/files/1/product.jpg",
  },
  {
    tag: "{{ top_recommendation_price }}",
    description: "Price of top recommended product",
    example: "$2,499",
  },
  {
    tag: "{{ quiz_category }}",
    description: "Category from the quiz (e.g., Saunas)",
    example: "Saunas",
  },
  {
    tag: "{{ quiz_goal }}",
    description: "Primary wellness goal from quiz",
    example: "detox and relaxation",
  },
  {
    tag: "{{ alt_recommendation_1 }}",
    description: "Second product recommendation",
    example: "Dynamic Saunas Barcelona 1-2 Person",
  },
  {
    tag: "{{ alt_recommendation_2 }}",
    description: "Third product recommendation",
    example: "SaunaLife Model X7 2-Person Barrel Sauna",
  },
  {
    tag: "{{ consultation_url }}",
    description: "Link to schedule a consultation",
    example: "https://peakprimalwellness.com/pages/consultation",
  },
  {
    tag: "{{ unsubscribe_url }}",
    description: "Unsubscribe link (auto-generated by Klaviyo)",
    example: "#",
  },
  {
    tag: "{{ brand_name }}",
    description: "Featured brand name for spotlight emails",
    example: "Golden Designs",
  },
  {
    tag: "{{ brand_story }}",
    description: "Brand story/quality narrative",
    example: "Since 2005, Golden Designs has been crafting premium saunas...",
  },
  {
    tag: "{{ offer_code }}",
    description: "Promotional discount code",
    example: "WELLNESS10",
  },
  {
    tag: "{{ offer_amount }}",
    description: "Discount amount or percentage",
    example: "10%",
  },
];

// ---------------------------------------------------------------------------
// Template generation helpers
// ---------------------------------------------------------------------------

function getCategoryContext(code: string): {
  cat: Category;
  content: typeof CATEGORY_CONTENT[number] | undefined;
} {
  const cat = CATEGORIES[code as keyof typeof CATEGORIES];
  const content = CATEGORY_CONTENT.find((c) => c.categoryCode === code);
  return { cat, content };
}

function wrapHtml(inner: string, preheader: string): string {
  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Peak Primal Wellness</title>
  <style>
    body { margin: 0; padding: 0; font-family: 'Helvetica Neue', Arial, sans-serif; background-color: #f4f4f4; color: #333333; }
    .wrapper { max-width: 600px; margin: 0 auto; background-color: #ffffff; }
    .header { background-color: #1a5632; padding: 24px 32px; text-align: center; }
    .header img { max-width: 180px; }
    .header h1 { color: #ffffff; font-size: 18px; margin: 8px 0 0; font-weight: 600; }
    .content { padding: 32px; }
    .content h2 { color: #1a5632; font-size: 22px; margin-top: 0; }
    .content p { font-size: 15px; line-height: 1.6; color: #555555; }
    .cta-btn { display: inline-block; background-color: #2d8a4e; color: #ffffff; padding: 14px 32px; text-decoration: none; border-radius: 6px; font-weight: 600; font-size: 15px; margin: 16px 0; }
    .cta-btn:hover { background-color: #1a5632; }
    .product-card { border: 1px solid #e5e5e5; border-radius: 8px; padding: 20px; margin: 16px 0; text-align: center; }
    .product-card img { max-width: 200px; margin-bottom: 12px; }
    .footer { background-color: #f8f8f8; padding: 24px 32px; text-align: center; font-size: 12px; color: #999999; }
    .footer a { color: #2d8a4e; text-decoration: none; }
    .preheader { display: none !important; max-height: 0; overflow: hidden; mso-hide: all; }
  </style>
</head>
<body>
  <div class="preheader">${preheader}</div>
  <div class="wrapper">
    <div class="header">
      <h1>Peak Primal Wellness</h1>
    </div>
    <div class="content">
${inner}
    </div>
    <div class="footer">
      <p>Peak Primal Wellness &middot; Your Home Wellness Experts</p>
      <p><a href="{{ consultation_url }}">Schedule a Free Consultation</a> &middot; <a href="{{ unsubscribe_url }}">Unsubscribe</a></p>
      <p style="font-size: 10px; color: #cccccc;">You're receiving this because you signed up at peakprimalwellness.com</p>
    </div>
  </div>
</body>
</html>`;
}

// ---------------------------------------------------------------------------
// Per-position template generators
// ---------------------------------------------------------------------------

function generateE1(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `{{ first_name|default:"Hey" }}, your personalized ${catName.toLowerCase()} recommendations are ready!`;
  const previewText = `We picked the best ${catName.toLowerCase()} based on your quiz answers.`;

  const inner = `      <h2>Your Personalized ${catName} Picks</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>Thanks for taking our ${catName} Finder Quiz! Based on your goals — <strong>{{ quiz_goal }}</strong> — we've hand-picked products that are the perfect match.</p>

      <div class="product-card">
        <img src="{{ top_recommendation_image }}" alt="{{ top_recommendation }}">
        <h3 style="color: #1a5632; margin: 8px 0 4px;">{{ top_recommendation }}</h3>
        <p style="font-size: 20px; font-weight: 700; color: #2d8a4e; margin: 4px 0;">{{ top_recommendation_price }}</p>
        <a href="{{ top_recommendation_url }}" class="cta-btn">View Your #1 Pick</a>
      </div>

      {% if alt_recommendation_1 %}
      <p style="font-size: 13px; color: #777;">Also worth considering: <strong>{{ alt_recommendation_1 }}</strong> and <strong>{{ alt_recommendation_2 }}</strong></p>
      {% endif %}

      <p>Have questions? Our wellness experts are just a click away.</p>
      <a href="{{ consultation_url }}" class="cta-btn" style="background-color: #555555;">Talk to an Expert — Free</a>`;

  return {
    position: "E1",
    day: 0,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nThanks for taking our ${catName} Finder Quiz! Based on your goals — {{ quiz_goal }} — here's your #1 pick:\n\n{{ top_recommendation }} — {{ top_recommendation_price }}\nView it here: {{ top_recommendation_url }}\n\nHave questions? Schedule a free consultation: {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "quiz_goal", "alt_recommendation", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [
      {
        condition: "{% if alt_recommendation_1 %}",
        description: "Show alternative recommendations if quiz returned multiple results",
        trueContent: "Display 2nd and 3rd product picks",
        falseContent: "Hide alternatives section",
      },
    ],
    purpose: "Personalized product recommendations",
  };
}

function generateE2(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `Everything you need to know about your {{ top_recommendation }}`;
  const previewText = `A deep dive into features, specs, and why it's perfect for you.`;

  const inner = `      <h2>Your {{ top_recommendation }}: The Full Story</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>Yesterday we shared your personalized ${catName.toLowerCase()} recommendation. Today, let's go deeper into why the <strong>{{ top_recommendation }}</strong> stands out.</p>

      <h3 style="color: #1a5632; font-size: 18px;">Key Features</h3>
      <ul style="color: #555; font-size: 15px; line-height: 1.8;">
        <li>Premium build quality with industry-leading warranty</li>
        <li>Designed for your wellness goals: {{ quiz_goal }}</li>
        <li>Easy setup — most customers are up and running in under an hour</li>
        <li>Trusted by thousands of home wellness enthusiasts</li>
      </ul>

      <div class="product-card">
        <img src="{{ top_recommendation_image }}" alt="{{ top_recommendation }}">
        <p style="font-size: 20px; font-weight: 700; color: #2d8a4e;">{{ top_recommendation_price }}</p>
        <a href="{{ top_recommendation_url }}" class="cta-btn">See Full Specs & Details</a>
      </div>

      <p>Wondering how it compares to other options? We'll cover that in a few days. For now, feel free to reach out — we're here to help.</p>
      <a href="{{ consultation_url }}" class="cta-btn" style="background-color: #555555;">Ask Us Anything</a>`;

  return {
    position: "E2",
    day: 1,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nLet's go deeper into why the {{ top_recommendation }} stands out.\n\nKey Features:\n- Premium build quality with industry-leading warranty\n- Designed for your goals: {{ quiz_goal }}\n- Easy setup\n- Trusted by thousands\n\nSee full details: {{ top_recommendation_url }}\n\nQuestions? {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "quiz_goal", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Detailed feature breakdown of #1 recommendation",
  };
}

function generateE3(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const ctx = getCategoryContext(code);
  const contentAreas = ctx.content?.contentAreas?.[0] ?? "Health, Wellness, Recovery";
  const benefits = contentAreas.split(",").map((b) => b.trim()).slice(0, 4);

  const subject = `The ${benefits[0]?.toLowerCase() ?? "health"} benefits of ${catName.toLowerCase()} (backed by science)`;
  const previewText = `How ${catName.toLowerCase()} can help you reach your {{ quiz_goal }} goals.`;

  const benefitListItems = benefits.map((b) => `        <li><strong>${b}</strong> — Research shows measurable improvements within weeks of consistent use.</li>`).join("\n");

  const inner = `      <h2>The Real Health Benefits of ${catName}</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>You mentioned <strong>{{ quiz_goal }}</strong> as your primary wellness goal. Here's the great news — ${catName.toLowerCase()} are clinically shown to deliver real results:</p>

      <ul style="color: #555; font-size: 15px; line-height: 1.8;">
${benefitListItems}
      </ul>

      <p>These aren't just claims — they're backed by peer-reviewed research. We've been gathering the latest studies so you can feel confident in your investment.</p>

      <a href="{{ top_recommendation_url }}" class="cta-btn">See How {{ top_recommendation }} Delivers These Benefits</a>

      <p style="margin-top: 24px; font-size: 13px; color: #777;">Want to dive deeper into the science? Reply to this email and we'll send you our research summary.</p>`;

  return {
    position: "E3",
    day: 3,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nYou mentioned {{ quiz_goal }} as your primary goal. Here's how ${catName.toLowerCase()} deliver:\n\n${benefits.map((b) => `- ${b}`).join("\n")}\n\nSee your recommendation: {{ top_recommendation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "quiz_goal", "top_recommendation"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Health benefits aligned with stated goals",
  };
}

function generateE4(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `Meet {{ brand_name }}: The people behind your ${catName.toLowerCase()}`;
  const previewText = `Quality, craftsmanship, and a warranty that proves it.`;

  const inner = `      <h2>Brand Spotlight: {{ brand_name }}</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>When you invest in a ${catName.toLowerCase()}, you want to know the people behind it stand by their product. That's why we partner with {{ brand_name }}.</p>

      <p>{{ brand_story }}</p>

      <h3 style="color: #1a5632; font-size: 18px;">Why We Trust {{ brand_name }}</h3>
      <ul style="color: #555; font-size: 15px; line-height: 1.8;">
        <li>Industry-leading warranty and customer support</li>
        <li>Thousands of verified 5-star reviews</li>
        <li>Premium materials and rigorous quality testing</li>
        <li>Continuous innovation in wellness technology</li>
      </ul>

      <a href="{{ top_recommendation_url }}" class="cta-btn">Explore {{ brand_name }} Products</a>

      <p style="margin-top: 24px;">At Peak Primal Wellness, we only carry brands we believe in. Every product on our site has been vetted by our wellness team.</p>`;

  return {
    position: "E4",
    day: 5,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nMeet {{ brand_name }} — the people behind your ${catName.toLowerCase()}.\n\n{{ brand_story }}\n\nWhy we trust them:\n- Industry-leading warranty\n- Thousands of 5-star reviews\n- Premium materials\n- Continuous innovation\n\nExplore: {{ top_recommendation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "brand_name", "brand_story", "top_recommendation"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Featured brand quality/warranty story",
  };
}

function generateE5(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `${catName} comparison: which type is right for you?`;
  const previewText = `Side-by-side breakdown to help you choose with confidence.`;

  const inner = `      <h2>${catName} Comparison Guide</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>One of the most common questions we hear: <em>"How do I know which type is right for me?"</em> Great question — let's break it down.</p>

      <table style="width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 14px;">
        <tr style="background-color: #1a5632; color: #ffffff;">
          <th style="padding: 12px; text-align: left;">Feature</th>
          <th style="padding: 12px; text-align: center;">Option A</th>
          <th style="padding: 12px; text-align: center;">Option B</th>
        </tr>
        <tr style="border-bottom: 1px solid #eee;">
          <td style="padding: 12px;">Best For</td>
          <td style="padding: 12px; text-align: center;">Targeted results</td>
          <td style="padding: 12px; text-align: center;">Full-body wellness</td>
        </tr>
        <tr style="border-bottom: 1px solid #eee; background-color: #f9f9f9;">
          <td style="padding: 12px;">Space Needed</td>
          <td style="padding: 12px; text-align: center;">Compact</td>
          <td style="padding: 12px; text-align: center;">Dedicated room/area</td>
        </tr>
        <tr style="border-bottom: 1px solid #eee;">
          <td style="padding: 12px;">Price Range</td>
          <td style="padding: 12px; text-align: center;">$$</td>
          <td style="padding: 12px; text-align: center;">$$$</td>
        </tr>
        <tr>
          <td style="padding: 12px;">Our Pick For You</td>
          <td colspan="2" style="padding: 12px; text-align: center; font-weight: 700; color: #2d8a4e;">{{ top_recommendation }}</td>
        </tr>
      </table>

      <p>Based on your quiz results, we think the <strong>{{ top_recommendation }}</strong> is the best fit for your goals.</p>

      <a href="{{ top_recommendation_url }}" class="cta-btn">See Why It's Our #1 Pick For You</a>`;

  return {
    position: "E5",
    day: 8,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nHow do you choose the right ${catName.toLowerCase()}? Here's a quick comparison.\n\nBased on your quiz, we recommend: {{ top_recommendation }}\n\nSee details: {{ top_recommendation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Comparison guide",
  };
}

function generateE6(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `"It changed my life" — real ${catName.toLowerCase()} stories`;
  const previewText = `See what other wellness enthusiasts are saying.`;

  const inner = `      <h2>Real Stories From Real Customers</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>Sometimes the best way to understand the impact of a ${catName.toLowerCase()} is to hear from people who already own one.</p>

      <div style="background-color: #f8faf9; border-left: 4px solid #2d8a4e; padding: 20px; margin: 20px 0; border-radius: 4px;">
        <p style="font-style: italic; color: #555; margin: 0 0 8px;">"I was skeptical at first, but after just two weeks I noticed a real difference in my recovery and sleep quality. Best investment I've made for my health."</p>
        <p style="font-weight: 600; color: #1a5632; margin: 0; font-size: 13px;">— Verified PPW Customer</p>
      </div>

      <div style="background-color: #f8faf9; border-left: 4px solid #2d8a4e; padding: 20px; margin: 20px 0; border-radius: 4px;">
        <p style="font-style: italic; color: #555; margin: 0 0 8px;">"The team at Peak Primal Wellness helped me choose the perfect setup for my space. Setup was a breeze and the quality exceeded my expectations."</p>
        <p style="font-weight: 600; color: #1a5632; margin: 0; font-size: 13px;">— Verified PPW Customer</p>
      </div>

      <p>Ready to start your own wellness journey?</p>
      <a href="{{ top_recommendation_url }}" class="cta-btn">View Your Recommendation</a>
      <br>
      <a href="{{ consultation_url }}" class="cta-btn" style="background-color: #555555;">Get Personalized Advice</a>`;

  return {
    position: "E6",
    day: 12,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nHear from real ${catName.toLowerCase()} owners:\n\n"I was skeptical at first, but after just two weeks I noticed a real difference..."\n— Verified Customer\n\nView your recommendation: {{ top_recommendation_url }}\nTalk to an expert: {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Case study, testimonial, lifestyle imagery",
  };
}

function generateE7(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `Setting up your ${catName.toLowerCase()}: easier than you think`;
  const previewText = `Everything you need to know before your new ${catName.toLowerCase()} arrives.`;

  const inner = `      <h2>Installation Made Simple</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>One of the top questions we get: <em>"How hard is it to set up?"</em> The answer: much easier than you'd expect.</p>

      <h3 style="color: #1a5632; font-size: 18px;">Quick Setup Checklist</h3>
      <ol style="color: #555; font-size: 15px; line-height: 1.8;">
        <li><strong>Choose your location</strong> — indoor or outdoor, with proper ventilation and clearance</li>
        <li><strong>Check electrical requirements</strong> — most models use a standard outlet; some require a dedicated circuit</li>
        <li><strong>Unbox and assemble</strong> — average setup time is 30-60 minutes with two people</li>
        <li><strong>First use</strong> — we recommend a break-in period before your first full session</li>
      </ol>

      <p>Every product from Peak Primal Wellness comes with detailed setup instructions, and our support team is available 7 days a week if you need help.</p>

      <a href="{{ top_recommendation_url }}" class="cta-btn">Check Setup Requirements for {{ top_recommendation }}</a>

      <p style="margin-top: 24px; font-size: 13px; color: #777;">Pro tip: Have questions about space or electrical requirements? Our experts can review your setup before you order. It's free!</p>
      <a href="{{ consultation_url }}" class="cta-btn" style="background-color: #555555;">Free Setup Consultation</a>`;

  return {
    position: "E7",
    day: 17,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nHow hard is it to set up a ${catName.toLowerCase()}? Much easier than you'd expect.\n\n1. Choose your location\n2. Check electrical requirements\n3. Unbox and assemble (30-60 min)\n4. Break-in period before first use\n\nCheck requirements: {{ top_recommendation_url }}\nFree setup consultation: {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Installation guide, common concerns",
  };
}

function generateE8(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `{{ first_name|default:"Hey" }}, still have questions about ${catName.toLowerCase()}?`;
  const previewText = `Our wellness experts are here to help — free consultation.`;

  const inner = `      <h2>We're Here to Help</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>Investing in a ${catName.toLowerCase()} is a big decision, and we want to make sure you feel 100% confident. That's why we offer free one-on-one consultations with our wellness experts.</p>

      <h3 style="color: #1a5632; font-size: 18px;">What We Can Help With</h3>
      <ul style="color: #555; font-size: 15px; line-height: 1.8;">
        <li>Product selection based on your goals and space</li>
        <li>Setup and electrical requirements</li>
        <li>Comparing models and brands</li>
        <li>Financing options and delivery logistics</li>
        <li>Any other questions you might have</li>
      </ul>

      <div style="text-align: center; margin: 24px 0;">
        <a href="{{ consultation_url }}" class="cta-btn">Schedule Your Free Consultation</a>
      </div>

      <p style="text-align: center; font-size: 13px; color: #777;">No pressure, no obligation — just honest expert advice.</p>

      <p>Or if you prefer, just reply to this email. We read and respond to every message.</p>`;

  return {
    position: "E8",
    day: 23,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nStill have questions? We offer free consultations:\n\n- Product selection\n- Setup requirements\n- Comparing models\n- Financing options\n\nSchedule here: {{ consultation_url }}\n\nOr just reply to this email — we respond to every message.`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Have questions? Let's talk",
  };
}

function generateE9(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `A little something to help you get started, {{ first_name|default:"friend" }}`;
  const previewText = `Exclusive offer on your recommended ${catName.toLowerCase()}.`;

  const inner = `      <h2>An Exclusive Offer, Just For You</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>You've done your research on ${catName.toLowerCase()} — you know the benefits, you've seen the reviews, and you've picked your top choice. Now let us make it a little easier.</p>

      {% if offer_code %}
      <div style="background-color: #f0faf3; border: 2px dashed #2d8a4e; border-radius: 8px; padding: 24px; text-align: center; margin: 24px 0;">
        <p style="font-size: 13px; color: #777; margin: 0 0 4px;">YOUR EXCLUSIVE CODE</p>
        <p style="font-size: 28px; font-weight: 800; color: #1a5632; margin: 0 0 4px; letter-spacing: 2px;">{{ offer_code }}</p>
        <p style="font-size: 18px; color: #2d8a4e; margin: 0;">Save {{ offer_amount }} on your order</p>
      </div>
      {% endif %}

      <div class="product-card">
        <img src="{{ top_recommendation_image }}" alt="{{ top_recommendation }}">
        <h3 style="color: #1a5632; margin: 8px 0 4px;">{{ top_recommendation }}</h3>
        <p style="font-size: 20px; font-weight: 700; color: #2d8a4e;">{{ top_recommendation_price }}</p>
        <a href="{{ top_recommendation_url }}" class="cta-btn">Shop Now</a>
      </div>

      <p style="font-size: 13px; color: #777; text-align: center;">We also offer financing options to make your wellness investment more manageable. <a href="{{ consultation_url }}" style="color: #2d8a4e;">Learn more</a></p>`;

  return {
    position: "E9",
    day: 30,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nYou've done your research. Now let us make it easier:\n\nUse code {{ offer_code }} to save {{ offer_amount }}.\n\n{{ top_recommendation }} — {{ top_recommendation_price }}\n{{ top_recommendation_url }}\n\nWe also offer financing: {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "offer_code", "offer_amount", "top_recommendation", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [
      {
        condition: "{% if offer_code %}",
        description: "Only show coupon section if an offer code is assigned",
        trueContent: "Display coupon code box with discount amount",
        falseContent: "Hide coupon section entirely",
      },
    ],
    purpose: "Special offer or financing (optional)",
  };
}

function generateE10(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `The complete ${catName.toLowerCase()} buyer's guide`;
  const previewText = `Everything you need to choose the perfect ${catName.toLowerCase()} for your home.`;

  const inner = `      <h2>Your ${catName} Buyer's Guide</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>Whether you're almost ready to buy or still exploring, this guide has everything you need to make the right decision.</p>

      <h3 style="color: #1a5632; font-size: 18px;">What's Inside</h3>
      <ul style="color: #555; font-size: 15px; line-height: 1.8;">
        <li><strong>Types and features</strong> — understand what matters most</li>
        <li><strong>Size and space planning</strong> — find the right fit for your home</li>
        <li><strong>Budget guide</strong> — options at every price point</li>
        <li><strong>Brand comparisons</strong> — our honest assessments</li>
        <li><strong>Setup requirements</strong> — what you need to know before ordering</li>
      </ul>

      <a href="{{ top_recommendation_url }}" class="cta-btn">Read the Full Guide</a>

      <div style="background-color: #f8faf9; border-radius: 8px; padding: 20px; margin: 24px 0; text-align: center;">
        <p style="margin: 0 0 8px; font-weight: 600; color: #1a5632;">Still not sure?</p>
        <p style="margin: 0 0 12px; font-size: 14px; color: #555;">Our experts have helped hundreds of customers find their perfect match.</p>
        <a href="{{ consultation_url }}" class="cta-btn" style="background-color: #555555;">Schedule a Free Consultation</a>
      </div>`;

  return {
    position: "E10",
    day: 37,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nYour ${catName} Buyer's Guide covers:\n- Types and features\n- Size and space planning\n- Budget guide\n- Brand comparisons\n- Setup requirements\n\nRead the guide: {{ top_recommendation_url }}\n\nStill not sure? Free consultation: {{ consultation_url }}`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "consultation_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Buyer's guide link, consultation reminder",
  };
}

function generateE11(code: string, catName: string): Omit<EmailTemplate, "templateName"> {
  const subject = `{{ first_name|default:"Hey" }}, want to keep hearing from us?`;
  const previewText = `Update your preferences or let us know what you'd like to see.`;

  const inner = `      <h2>Stay Connected?</h2>
      <p>Hi {{ first_name|default:"there" }},</p>
      <p>It's been a few weeks since you took our ${catName} quiz, and we want to make sure we're sending you content you actually find helpful.</p>

      <p>Here are your options:</p>

      <div style="margin: 20px 0;">
        <a href="{{ top_recommendation_url }}" class="cta-btn" style="display: block; text-align: center; margin-bottom: 12px;">I'm Still Interested — Keep the Tips Coming</a>
        <a href="{{ consultation_url }}" class="cta-btn" style="display: block; text-align: center; margin-bottom: 12px; background-color: #555555;">I'm Ready to Buy — Connect Me With an Expert</a>
        <a href="{{ unsubscribe_url }}" style="display: block; text-align: center; font-size: 13px; color: #999; text-decoration: underline;">I'd like to unsubscribe</a>
      </div>

      <p>No hard feelings either way — we're here whenever you're ready. Your wellness journey is yours, and we're happy to be part of it whenever the time is right.</p>

      <p style="font-size: 13px; color: #777;">— The Peak Primal Wellness Team</p>`;

  return {
    position: "E11",
    day: 45,
    categoryCode: code,
    categoryName: catName,
    subject,
    previewText,
    htmlBody: wrapHtml(inner, previewText),
    plainText: `Hi {{ first_name|default:"there" }},\n\nWant to keep hearing from us about ${catName.toLowerCase()}?\n\n- Still interested? We'll keep the tips coming.\n- Ready to buy? Let's connect: {{ consultation_url }}\n- Want to unsubscribe? No hard feelings: {{ unsubscribe_url }}\n\n— The Peak Primal Wellness Team`,
    variables: KLAVIYO_VARIABLES.filter((v) =>
      ["first_name", "top_recommendation", "consultation_url", "unsubscribe_url"].some((k) => v.tag.includes(k))
    ),
    conditionals: [],
    purpose: "Preference update, stay subscribed?",
  };
}

// ---------------------------------------------------------------------------
// Main generator
// ---------------------------------------------------------------------------

const POSITION_GENERATORS: Record<string, (code: string, catName: string) => Omit<EmailTemplate, "templateName">> = {
  E1: generateE1,
  E2: generateE2,
  E3: generateE3,
  E4: generateE4,
  E5: generateE5,
  E6: generateE6,
  E7: generateE7,
  E8: generateE8,
  E9: generateE9,
  E10: generateE10,
  E11: generateE11,
};

/**
 * Generate a single email template for a given category and position.
 */
export function generateEmailTemplate(
  categoryCode: string,
  position: string
): EmailTemplate | null {
  const cat = CATEGORIES[categoryCode as keyof typeof CATEGORIES];
  if (!cat) return null;

  const generator = POSITION_GENERATORS[position];
  if (!generator) return null;

  const templateName = buildAssetName("template", categoryCode, "Nurture", position);
  const result = generator(categoryCode, cat.name);

  return {
    templateName,
    ...result,
  };
}

/**
 * Generate all 11 nurture email templates for a category.
 */
export function generateAllTemplatesForCategory(
  categoryCode: string
): EmailTemplate[] {
  return NURTURE_EMAIL_POSITIONS.map((pos) =>
    generateEmailTemplate(categoryCode, pos.position)
  ).filter((t): t is EmailTemplate => t !== null);
}

/**
 * Get available positions for template generation.
 */
export function getAvailablePositions(): EmailPosition[] {
  return NURTURE_EMAIL_POSITIONS;
}
